ExUnit.start()
Code.compiler_options(ignore_module_conflict: true)
Code.compile_file("challenges/euler_2.exs")
Code.compile_file("challenges/euler_5.exs")
Code.compile_file("challenges/euler_6.exs")
Code.compile_file("challenges/euler_7.exs")
Code.compile_file("challenges/euler_8.exs")
