ExUnit.start()
Code.compiler_options(ignore_module_conflict: true)
Code.compile_file("challenges/001.exs")
Code.compile_file("challenges/002.exs")
Code.compile_file("challenges/003.exs")
Code.compile_file("challenges/004.exs")
Code.compile_file("challenges/005.exs")
Code.compile_file("challenges/006.exs")
Code.compile_file("challenges/007.exs")
Code.compile_file("challenges/008.exs")
Code.compile_file("challenges/009.exs")
Code.compile_file("challenges/010.exs")
